// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmuxuplanltdrehjsfoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tdXh1cGxhbmx0ZHJlaGpzZm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTgwMzIsImV4cCI6MjA2NTAzNDAzMn0.EQ_2vjO28xCyPuZ8nW5aFZPbyeEkIMwHn3rcydHCihg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);